/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AimCarMask: typeof import('./src/components/AimCarMask.vue')['default']
    CarIdCard: typeof import('./src/components/CarIdCard.vue')['default']
    copy: typeof import('./src/components/Step3 copy.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    PorscheIdCard: typeof import('./src/components/PorscheIdCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1: typeof import('./src/components/Step1.vue')['default']
    Step2: typeof import('./src/components/Step2.vue')['default']
    Step3: typeof import('./src/components/Step3.vue')['default']
    Step4: typeof import('./src/components/Step4.vue')['default']
    Step5: typeof import('./src/components/Step5.vue')['default']
    SwiperCar: typeof import('./src/components/SwiperCar.vue')['default']
    TheButton: typeof import('./src/components/TheButton.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheForm: typeof import('./src/components/TheForm.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
